services:
  postgres:
    image: postgres:16
    container_name: nest-test-db
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nest_test}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
